//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceb.MerlinTool.AuthenticationWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", ConfigurationName="AuthenticationWebService.IAuthenticationWebService")]
    public interface IAuthenticationWebService {
        
        // CODEGEN: Generating message contract since message AuthenticateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/Authenticate", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(CEB.CustomControls.AuthenticationWebServiceReference.GeneralFault), Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateGeneralF" +
            "aultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/CEB.CWS.Infra.Contracts.Exceptions")]
        Ceb.MerlinTool.AuthenticationWebService.AuthenticateResponse Authenticate(Ceb.MerlinTool.AuthenticationWebService.AuthenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/Authenticate", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateResponse" +
            "")]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.AuthenticateResponse> AuthenticateAsync(Ceb.MerlinTool.AuthenticationWebService.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since message AuthenticateWebv2Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateWebv2", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateWebv2Res" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CEB.CustomControls.AuthenticationWebServiceReference.GeneralFault), Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateWebv2Gen" +
            "eralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/CEB.CWS.Infra.Contracts.Exceptions")]
        Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Response AuthenticateWebv2(Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateWebv2", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateWebv2Res" +
            "ponse")]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Response> AuthenticateWebv2Async(Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Request request);
        
        // CODEGEN: Generating message contract since message ValidateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/Validate", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ValidateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CEB.CustomControls.AuthenticationWebServiceReference.GeneralFault), Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ValidateGeneralFault" +
            "Fault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/CEB.CWS.Infra.Contracts.Exceptions")]
        Ceb.MerlinTool.AuthenticationWebService.ValidateResponse Validate(Ceb.MerlinTool.AuthenticationWebService.ValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/Validate", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ValidateResponse")]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.ValidateResponse> ValidateAsync(Ceb.MerlinTool.AuthenticationWebService.ValidateRequest request);
        
        // CODEGEN: Generating message contract since message ImpersonateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/Impersonate", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ImpersonateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CEB.CustomControls.AuthenticationWebServiceReference.GeneralFault), Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ImpersonateGeneralFa" +
            "ultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/CEB.CWS.Infra.Contracts.Exceptions")]
        Ceb.MerlinTool.AuthenticationWebService.ImpersonateResponse Impersonate(Ceb.MerlinTool.AuthenticationWebService.ImpersonateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/Impersonate", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ImpersonateResponse")]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.ImpersonateResponse> ImpersonateAsync(Ceb.MerlinTool.AuthenticationWebService.ImpersonateRequest request);
        
        // CODEGEN: Generating message contract since message AuthenticateTokenRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateToken", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateTokenRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CEB.CustomControls.AuthenticationWebServiceReference.GeneralFault), Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateTokenGen" +
            "eralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/CEB.CWS.Infra.Contracts.Exceptions")]
        Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenResponse AuthenticateToken(Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateToken", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/AuthenticateTokenRes" +
            "ponse")]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenResponse> AuthenticateTokenAsync(Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenRequest request);
        
        // CODEGEN: Generating message contract since message ValidateSecurityTokenRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ValidateSecurityToke" +
            "n", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ValidateSecurityToke" +
            "nResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CEB.CustomControls.AuthenticationWebServiceReference.GeneralFault), Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ValidateSecurityToke" +
            "nGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/CEB.CWS.Infra.Contracts.Exceptions")]
        Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenResponse ValidateSecurityToken(Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ValidateSecurityToke" +
            "n", ReplyAction="CEB.CWS.Infra.WebService.Contracts/IAuthenticationWebService/ValidateSecurityToke" +
            "nResponse")]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenResponse> ValidateSecurityTokenAsync(Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authenticate", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=2)]
        public string identitySystem;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string username, string password, string identitySystem) {
            this.CebHeader = CebHeader;
            this.username = username;
            this.password = password;
            this.identitySystem = identitySystem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateResponse", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public CEB.CustomControls.AuthenticationWebServiceReference.AuthenticationResponse AuthenticateResult;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(CEB.CustomControls.AuthenticationWebServiceReference.AuthenticationResponse AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateWebv2", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class AuthenticateWebv2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public CEB.CustomControls.AuthenticationWebServiceReference.UserCredentials userCredentials;
        
        public AuthenticateWebv2Request() {
        }
        
        public AuthenticateWebv2Request(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, CEB.CustomControls.AuthenticationWebServiceReference.UserCredentials userCredentials) {
            this.CebHeader = CebHeader;
            this.userCredentials = userCredentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateWebv2Response", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class AuthenticateWebv2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public CEB.CustomControls.AuthenticationWebServiceReference.AuthenticateResult AuthenticateWebv2Result;
        
        public AuthenticateWebv2Response() {
        }
        
        public AuthenticateWebv2Response(CEB.CustomControls.AuthenticationWebServiceReference.AuthenticateResult AuthenticateWebv2Result) {
            this.AuthenticateWebv2Result = AuthenticateWebv2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Validate", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public string serviceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=1)]
        public string userName;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string serviceName, string userName) {
            this.CebHeader = CebHeader;
            this.serviceName = serviceName;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateResponse", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public CEB.CustomControls.AuthenticationWebServiceReference.ValidateResult ValidateResult;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(CEB.CustomControls.AuthenticationWebServiceReference.ValidateResult ValidateResult) {
            this.ValidateResult = ValidateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Impersonate", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class ImpersonateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=1)]
        public string contactCrmId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=2)]
        public string impersonatingUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=3)]
        public string programAcronym;
        
        public ImpersonateRequest() {
        }
        
        public ImpersonateRequest(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string email, string contactCrmId, string impersonatingUserEmail, string programAcronym) {
            this.CebHeader = CebHeader;
            this.email = email;
            this.contactCrmId = contactCrmId;
            this.impersonatingUserEmail = impersonatingUserEmail;
            this.programAcronym = programAcronym;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImpersonateResponse", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class ImpersonateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public CEB.CustomControls.AuthenticationWebServiceReference.ImpersonateResponse ImpersonateResult;
        
        public ImpersonateResponse() {
        }
        
        public ImpersonateResponse(CEB.CustomControls.AuthenticationWebServiceReference.ImpersonateResponse ImpersonateResult) {
            this.ImpersonateResult = ImpersonateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateToken", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class AuthenticateTokenRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public string token;
        
        public AuthenticateTokenRequest() {
        }
        
        public AuthenticateTokenRequest(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string token) {
            this.CebHeader = CebHeader;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateTokenResponse", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class AuthenticateTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public CEB.CustomControls.AuthenticationWebServiceReference.AuthenticateTokenResponse AuthenticateTokenResult;
        
        public AuthenticateTokenResponse() {
        }
        
        public AuthenticateTokenResponse(CEB.CustomControls.AuthenticationWebServiceReference.AuthenticateTokenResponse AuthenticateTokenResult) {
            this.AuthenticateTokenResult = AuthenticateTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateSecurityToken", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class ValidateSecurityTokenRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public string securityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=1)]
        public string serviceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=2)]
        public string methodName;
        
        public ValidateSecurityTokenRequest() {
        }
        
        public ValidateSecurityTokenRequest(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string securityToken, string serviceName, string methodName) {
            this.CebHeader = CebHeader;
            this.securityToken = securityToken;
            this.serviceName = serviceName;
            this.methodName = methodName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateSecurityTokenResponse", WrapperNamespace="CEB.CWS.Infra.WebService.Contracts", IsWrapped=true)]
    public partial class ValidateSecurityTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CEB.CWS.Infra.WebService.Contracts", Order=0)]
        public CEB.CustomControls.AuthenticationWebServiceReference.ValidateResponse ValidateSecurityTokenResult;
        
        public ValidateSecurityTokenResponse() {
        }
        
        public ValidateSecurityTokenResponse(CEB.CustomControls.AuthenticationWebServiceReference.ValidateResponse ValidateSecurityTokenResult) {
            this.ValidateSecurityTokenResult = ValidateSecurityTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationWebServiceChannel : Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationWebServiceClient : System.ServiceModel.ClientBase<Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService>, Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService {
        
        public AuthenticationWebServiceClient() {
        }
        
        public AuthenticationWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ceb.MerlinTool.AuthenticationWebService.AuthenticateResponse Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.Authenticate(Ceb.MerlinTool.AuthenticationWebService.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public CEB.CustomControls.AuthenticationWebServiceReference.AuthenticationResponse Authenticate(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string username, string password, string identitySystem) {
            Ceb.MerlinTool.AuthenticationWebService.AuthenticateRequest inValue = new Ceb.MerlinTool.AuthenticationWebService.AuthenticateRequest();
            inValue.CebHeader = CebHeader;
            inValue.username = username;
            inValue.password = password;
            inValue.identitySystem = identitySystem;
            Ceb.MerlinTool.AuthenticationWebService.AuthenticateResponse retVal = ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).Authenticate(inValue);
            return retVal.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.AuthenticateResponse> Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.AuthenticateAsync(Ceb.MerlinTool.AuthenticationWebService.AuthenticateRequest request) {
            return base.Channel.AuthenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.AuthenticateResponse> AuthenticateAsync(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string username, string password, string identitySystem) {
            Ceb.MerlinTool.AuthenticationWebService.AuthenticateRequest inValue = new Ceb.MerlinTool.AuthenticationWebService.AuthenticateRequest();
            inValue.CebHeader = CebHeader;
            inValue.username = username;
            inValue.password = password;
            inValue.identitySystem = identitySystem;
            return ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).AuthenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Response Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.AuthenticateWebv2(Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Request request) {
            return base.Channel.AuthenticateWebv2(request);
        }
        
        public CEB.CustomControls.AuthenticationWebServiceReference.AuthenticateResult AuthenticateWebv2(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, CEB.CustomControls.AuthenticationWebServiceReference.UserCredentials userCredentials) {
            Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Request inValue = new Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Request();
            inValue.CebHeader = CebHeader;
            inValue.userCredentials = userCredentials;
            Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Response retVal = ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).AuthenticateWebv2(inValue);
            return retVal.AuthenticateWebv2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Response> Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.AuthenticateWebv2Async(Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Request request) {
            return base.Channel.AuthenticateWebv2Async(request);
        }
        
        public System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Response> AuthenticateWebv2Async(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, CEB.CustomControls.AuthenticationWebServiceReference.UserCredentials userCredentials) {
            Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Request inValue = new Ceb.MerlinTool.AuthenticationWebService.AuthenticateWebv2Request();
            inValue.CebHeader = CebHeader;
            inValue.userCredentials = userCredentials;
            return ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).AuthenticateWebv2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ceb.MerlinTool.AuthenticationWebService.ValidateResponse Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.Validate(Ceb.MerlinTool.AuthenticationWebService.ValidateRequest request) {
            return base.Channel.Validate(request);
        }
        
        public CEB.CustomControls.AuthenticationWebServiceReference.ValidateResult Validate(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string serviceName, string userName) {
            Ceb.MerlinTool.AuthenticationWebService.ValidateRequest inValue = new Ceb.MerlinTool.AuthenticationWebService.ValidateRequest();
            inValue.CebHeader = CebHeader;
            inValue.serviceName = serviceName;
            inValue.userName = userName;
            Ceb.MerlinTool.AuthenticationWebService.ValidateResponse retVal = ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).Validate(inValue);
            return retVal.ValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.ValidateResponse> Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.ValidateAsync(Ceb.MerlinTool.AuthenticationWebService.ValidateRequest request) {
            return base.Channel.ValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.ValidateResponse> ValidateAsync(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string serviceName, string userName) {
            Ceb.MerlinTool.AuthenticationWebService.ValidateRequest inValue = new Ceb.MerlinTool.AuthenticationWebService.ValidateRequest();
            inValue.CebHeader = CebHeader;
            inValue.serviceName = serviceName;
            inValue.userName = userName;
            return ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).ValidateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ceb.MerlinTool.AuthenticationWebService.ImpersonateResponse Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.Impersonate(Ceb.MerlinTool.AuthenticationWebService.ImpersonateRequest request) {
            return base.Channel.Impersonate(request);
        }
        
        public CEB.CustomControls.AuthenticationWebServiceReference.ImpersonateResponse Impersonate(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string email, string contactCrmId, string impersonatingUserEmail, string programAcronym) {
            Ceb.MerlinTool.AuthenticationWebService.ImpersonateRequest inValue = new Ceb.MerlinTool.AuthenticationWebService.ImpersonateRequest();
            inValue.CebHeader = CebHeader;
            inValue.email = email;
            inValue.contactCrmId = contactCrmId;
            inValue.impersonatingUserEmail = impersonatingUserEmail;
            inValue.programAcronym = programAcronym;
            Ceb.MerlinTool.AuthenticationWebService.ImpersonateResponse retVal = ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).Impersonate(inValue);
            return retVal.ImpersonateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.ImpersonateResponse> Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.ImpersonateAsync(Ceb.MerlinTool.AuthenticationWebService.ImpersonateRequest request) {
            return base.Channel.ImpersonateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.ImpersonateResponse> ImpersonateAsync(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string email, string contactCrmId, string impersonatingUserEmail, string programAcronym) {
            Ceb.MerlinTool.AuthenticationWebService.ImpersonateRequest inValue = new Ceb.MerlinTool.AuthenticationWebService.ImpersonateRequest();
            inValue.CebHeader = CebHeader;
            inValue.email = email;
            inValue.contactCrmId = contactCrmId;
            inValue.impersonatingUserEmail = impersonatingUserEmail;
            inValue.programAcronym = programAcronym;
            return ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).ImpersonateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenResponse Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.AuthenticateToken(Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenRequest request) {
            return base.Channel.AuthenticateToken(request);
        }
        
        public CEB.CustomControls.AuthenticationWebServiceReference.AuthenticateTokenResponse AuthenticateToken(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string token) {
            Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenRequest inValue = new Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenRequest();
            inValue.CebHeader = CebHeader;
            inValue.token = token;
            Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenResponse retVal = ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).AuthenticateToken(inValue);
            return retVal.AuthenticateTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenResponse> Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.AuthenticateTokenAsync(Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenRequest request) {
            return base.Channel.AuthenticateTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenResponse> AuthenticateTokenAsync(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string token) {
            Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenRequest inValue = new Ceb.MerlinTool.AuthenticationWebService.AuthenticateTokenRequest();
            inValue.CebHeader = CebHeader;
            inValue.token = token;
            return ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).AuthenticateTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenResponse Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.ValidateSecurityToken(Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenRequest request) {
            return base.Channel.ValidateSecurityToken(request);
        }
        
        public CEB.CustomControls.AuthenticationWebServiceReference.ValidateResponse ValidateSecurityToken(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string securityToken, string serviceName, string methodName) {
            Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenRequest inValue = new Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenRequest();
            inValue.CebHeader = CebHeader;
            inValue.securityToken = securityToken;
            inValue.serviceName = serviceName;
            inValue.methodName = methodName;
            Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenResponse retVal = ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).ValidateSecurityToken(inValue);
            return retVal.ValidateSecurityTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenResponse> Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService.ValidateSecurityTokenAsync(Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenRequest request) {
            return base.Channel.ValidateSecurityTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenResponse> ValidateSecurityTokenAsync(CEB.CustomControls.AuthenticationWebServiceReference.Header CebHeader, string securityToken, string serviceName, string methodName) {
            Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenRequest inValue = new Ceb.MerlinTool.AuthenticationWebService.ValidateSecurityTokenRequest();
            inValue.CebHeader = CebHeader;
            inValue.securityToken = securityToken;
            inValue.serviceName = serviceName;
            inValue.methodName = methodName;
            return ((Ceb.MerlinTool.AuthenticationWebService.IAuthenticationWebService)(this)).ValidateSecurityTokenAsync(inValue);
        }
    }
}
